{{- if .Values.installCRDs }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.5
  name: popsignerrestores.popsigner.com
  labels:
    {{- include "popsigner-operator.labels" . | nindent 4 }}
spec:
  group: popsigner.com
  names:
    kind: POPSignerRestore
    listKind: POPSignerRestoreList
    plural: popsignerrestores
    singular: popsignerrestore
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    - jsonPath: .spec.backupRef.name
      name: Backup
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1
    schema:
      openAPIV3Schema:
        description: POPSignerRestore is the Schema for the popsignerrestores API
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: POPSignerRestoreSpec defines the desired state
            properties:
              backupRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              clusterRef:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              components:
                items:
                  type: string
                type: array
              options:
                properties:
                  stopApplications:
                    default: true
                    type: boolean
                  verifyBackup:
                    default: true
                    type: boolean
                type: object
              source:
                type: object
                x-kubernetes-preserve-unknown-fields: true
            required:
            - clusterRef
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
{{- end }}
