apiVersion: v2
name: banhbaoring-operator
description: BanhBaoRing Kubernetes Operator - Deploy and manage secure key infrastructure
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - key-management
  - openbao
  - vault
  - celestia
  - rollups
  - signing
maintainers:
  - name: BanhBaoRing Team
    url: https://github.com/Bidon15/banhbaoring
home: https://banhbaoring.io
sources:
  - https://github.com/Bidon15/banhbaoring
icon: https://banhbaoring.io/logo.png
