apiVersion: v2
name: popsigner-operator
description: POPSigner Kubernetes Operator - Deploy and manage secure key infrastructure
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - key-management
  - openbao
  - vault
  - celestia
  - rollups
  - signing
  - popsigner
maintainers:
  - name: POPSigner Team
    url: https://github.com/Bidon15/banhbaoring
home: https://popsigner.com
sources:
  - https://github.com/Bidon15/banhbaoring
icon: https://popsigner.com/logo.png
