apiVersion: popsigner.com/v1
kind: POPSignerCluster
metadata:
  name: dev
  namespace: popsigner
spec:
  domain: keys.local
  openbao:
    replicas: 1
    storage:
      size: 1Gi
  database:
    managed: true
    storage:
      size: 1Gi
  redis:
    managed: true
    mode: standalone
