apiVersion: banhbaoring.io/v1
kind: BanhBaoRingCluster
metadata:
  name: dev
  namespace: banhbaoring
spec:
  domain: keys.local
  openbao:
    replicas: 1
    storage:
      size: 1Gi
  database:
    managed: true
    storage:
      size: 1Gi
  redis:
    managed: true
    mode: standalone
